name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  yaml-lint:
    name: YAML lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML
        run: yamllint .

  helm-check:
    name: Helm validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Add OpenTelemetry Helm repository
        run: |
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo update

      - name: Helm lint
        run: |
          helm lint \
            open-telemetry/opentelemetry-demo \
            --values helm/otel-demo-values.yaml